from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("giocatori/", views.users_list, name="users_list"),
    path("giocatori/nuovo/", views.user_create, name="user_create"),
    path("accedi/", views.login_view, name="login"),
    path("esci/", views.logout_view, name="logout"),
    path("community/", views.community, name="community"),
    path("community.json", views.community_json, name="community_json"),
    path("notifiche.json", views.notifications_json, name="notifications_json"),
    path("notifiche/lette.json", views.notifications_read_json, name="notifications_read_json"),
    path("sfide/nuova/<int:user_id>/", views.challenge_new, name="challenge_new"),
    path("sfide/<int:invite_id>/azione/", views.challenge_action, name="challenge_action"),
    path("impara/", views.learn_index, name="learn_index"),
    path("impara/<slug:code>/", views.learn_lesson, name="learn_lesson"),
    path(
        "impara/<slug:code>/progresso.json",
        views.learn_progress_json,
        name="learn_progress_json",
    ),
    path("giocatori/<int:user_id>/", views.user_detail, name="user_detail"),
    path("giocatori/<int:user_id>/statistiche/", views.user_stats, name="user_stats"),
    path("gruppi/", views.groups, name="groups"),
    path("gruppi/proponi/", views.group_propose, name="group_propose"),
    path(
        "gruppi/proposte/<int:proposal_id>/vota/",
        views.proposal_vote,
        name="proposal_vote",
    ),
    path("gruppi/<int:group_id>/", views.group_detail, name="group_detail"),
    path("gruppi/<int:group_id>/azione/", views.group_action, name="group_action"),
    path(
        "gruppi/<int:group_id>/sfide/nuova/",
        views.group_match_create,
        name="group_match_create",
    ),
    path("gruppi/sfide/<int:match_id>/", views.group_match_detail, name="group_match_detail"),
    path(
        "gruppi/sfide/<int:match_id>/azione/",
        views.group_match_action,
        name="group_match_action",
    ),
    path(
        "gruppi/inviti/<int:invite_id>/rispondi/",
        views.group_invite_respond,
        name="group_invite_respond",
    ),
    path("tornei/", views.tournaments_page, name="tournaments"),
    path("tornei/<int:tournament_id>/", views.tournament_detail, name="tournament_detail"),
    path(
        "tornei/<int:tournament_id>/azione/",
        views.tournament_action,
        name="tournament_action",
    ),
    path("classifiche/", views.rankings, name="rankings"),
    path("puzzle/", views.puzzles_list, name="puzzles"),
    path("puzzle/<int:puzzle_id>/", views.puzzle_play, name="puzzle_play"),
    path(
        "puzzle/<int:puzzle_id>/tentativo.json",
        views.puzzle_attempt_json,
        name="puzzle_attempt_json",
    ),
    path("arena/", views.arena, name="arena"),
    path("arena/tornei/<int:tournament_id>/", views.arena_tournament, name="arena_tournament"),
    path(
        "arena/tornei/<int:tournament_id>/stato.json",
        views.arena_tournament_json,
        name="arena_tournament_json",
    ),
    path("partite/registra/", views.match_create, name="match_create"),
    path("gioca/", views.play_hub, name="play_hub"),
    path("gioca/nuova/", views.play_setup, name="play_setup"),
    path("partite/<int:session_id>/", views.play, name="play"),
    path("partite/<int:session_id>/guarda/", views.watch, name="watch"),
    path("partite/<int:session_id>/mossa/", views.play_move, name="play_move"),
    path("partite/<int:session_id>/mossa.json", views.play_move_json, name="play_move_json"),
    path("partite/<int:session_id>/stato.json", views.play_state_json, name="play_state_json"),
    path("partite/<int:session_id>/replay.json", views.play_replay_json, name="play_replay_json"),
    path("partite/<int:session_id>/nota.json", views.play_note_json, name="play_note_json"),
    path(
        "partite/<int:session_id>/spiega.json",
        views.play_explain_json,
        name="play_explain_json",
    ),
    path("partite/<int:session_id>/hint.json", views.play_hint_json, name="play_hint_json"),
    path("partite/<int:session_id>/fine.json", views.play_endgame_json, name="play_endgame_json"),
    path(
        "partite/<int:session_id>/analisi.json",
        views.play_analysis_json,
        name="play_analysis_json",
    ),
    path("admin/", views.admin, name="admin"),
    path("admin/ia/", views.admin_ai, name="admin_ai"),
]
