# ruff: noqa: E501 - dizionario: una voce per riga vale più del limite di colonna
"""Catalogo italiano → inglese dei DATI del backend (vedi ``i18n.py``).

Un dizionario piatto: chiave = stringa sorgente italiana, valore = inglese.
Copre i messaggi d'errore dei router, i motivi/consiglio del tilt, le
debolezze e i bias del profilo, le etichette dei parametri admin e i nomi
delle aperture. Le stringhe non presenti passano invariate (fallback).
"""

CATALOG_EN = {
    ". Riprova tra ~{min} minuti — intanto: ": ". Try again in ~{min} minutes — meanwhile: ",
    "Alias già in uso": "Alias already in use",
    "Analisi post-partita: tempo per posizione (millisecondi)": "Post-game analysis: time per position (milliseconds)",
    "Apertura Bird": "Bird's Opening",
    "Apertura Catalana": "Catalan Opening",
    "Apertura Inglese": "English Opening",
    "Apertura Réti": "Réti Opening",
    "Apertura di Donna": "Queen's Pawn Opening",
    "Apertura di Re": "King's Pawn Opening",
    "Attacco Est-Indiano": "King's Indian Attack",
    "Attacco Torre": "Torre Attack",
    "Attacco Trompowsky": "Trompowsky Attack",
    "Azione non valida (offer/accept/decline)": "Invalid action (offer/accept/decline)",
    "Badge di qualità sulle mosse (scacchi, valutati da Stockfish)": "Move quality badges (chess, judged by Stockfish)",
    "Benoni moderna": "Modern Benoni",
    "Bilancio negativo: in generale tende a perdere.": "Negative record: tends to lose overall.",
    "Budget del motore per il suggerimento (millisecondi)": "Engine budget for the hint (milliseconds)",
    "Cache del profilo avversario (secondi; 0 = ricostruito a ogni uso)": "Opponent profile cache (seconds; 0 = rebuilt on every use)",
    "Caro-Kann classica": "Classical Caro-Kann",
    "Caro-Kann di cambio": "Exchange Caro-Kann",
    "Caro-Kann, attacco Panov": "Caro-Kann, Panov Attack",
    "Caro-Kann, variante d'avanzata": "Caro-Kann, Advance Variation",
    "Circuit breaker: errori consecutivi che sospendono un provider remoto": "Circuit breaker: consecutive errors that suspend a remote provider",
    "Circuit breaker: pausa prima di riprovare il provider (secondi)": "Circuit breaker: pause before retrying the provider (seconds)",
    "Coazione alla cattura": "Capture compulsion",
    "Commentatore LLM della partita (usa il provider IA attivo)": "LLM game commentator (uses the active AI provider)",
    "Commette blunder frequenti ({n} per partita, analisi motore su {games} partite).": "Makes frequent blunders ({n} per game, engine analysis over {games} games).",
    "Concorrenti sconosciuti: {codes}": "Unknown competitors: {codes}",
    "Consenti la registrazione di nuovi giocatori": "Allow new player registrations",
    "Contro l'IA la patta d'accordo non è disponibile": "Draw by agreement is not available against the AI",
    "Credenziali non valide": "Invalid credentials",
    "Debolezza nei finali: cede nelle partite lunghe.": "Endgame weakness: cracks in long games.",
    "Difesa Alekhine": "Alekhine's Defence",
    "Difesa Caro-Kann": "Caro-Kann Defence",
    "Difesa Est-Indiana": "King's Indian Defence",
    "Difesa Filidor": "Philidor Defence",
    "Difesa Francese": "French Defence",
    "Difesa Grünfeld": "Grünfeld Defence",
    "Difesa Moderna": "Modern Defence",
    "Difesa Nimzo-Indiana": "Nimzo-Indian Defence",
    "Difesa Olandese": "Dutch Defence",
    "Difesa Olandese classica": "Classical Dutch",
    "Difesa Ovest-Indiana": "Queen's Indian Defence",
    "Difesa Petroff (Russa)": "Petroff (Russian) Defence",
    "Difesa Pirc": "Pirc Defence",
    "Difesa Pirc (attacco austriaco)": "Pirc Defence (Austrian Attack)",
    "Difesa Scandinava": "Scandinavian Defence",
    "Difesa Semi-Slava": "Semi-Slav Defence",
    "Difesa Siciliana": "Sicilian Defence",
    "Difesa Slava": "Slav Defence",
    "Difesa Tarrasch": "Tarrasch Defence",
    "Difesa dei due cavalli": "Two Knights Defence",
    "Difesa dei due cavalli (attacco Ng5)": "Two Knights Defence (Ng5 Attack)",
    "Difesa dei due cavalli (moderna d3)": "Two Knights Defence (Modern d3)",
    "Disponibile solo per gli scacchi": "Available for chess only",
    "Donna precoce": "Early queen",
    "Durata dell'animazione di spostamento dei pezzi (millisecondi; 0 = nessuna)": "Piece movement animation duration (milliseconds; 0 = none)",
    "Durata della sessione di accesso (ore)": "Login session duration (hours)",
    "Effetto sonoro delle mosse": "Move sound effect",
    "Elo simulato di Stockfish (0 = piena forza; range utile 1320-3190)": "Simulated Stockfish Elo (0 = full strength; useful range 1320-3190)",
    "Email già registrata": "Email already registered",
    "Est-Indiana classica": "Classical King's Indian",
    "Est-Indiana, variante Sämisch": "King's Indian, Sämisch Variation",
    "Export GIF non supportato per questo gioco": "GIF export not supported for this game",
    "FEN non valida": "Invalid FEN",
    "FEN non valida: {err}": "Invalid FEN: {err}",
    "Fai una pausa di dieci minuti lontano dalla scacchiera, poi riscaldati con una lezione della sezione «Impara» (i finali elementari sono perfetti) prima di rigiocare una partita che conta.": "Take a ten-minute break away from the board, then warm up with a lesson from the “Learn” section (elementary endgames are perfect) before playing a game that counts again.",
    "Finestra di presenza online (secondi dall'ultimo heartbeat)": "Online presence window (seconds since last heartbeat)",
    "Formato ufficiale FIDE: suggerimenti non ammessi": "Official FIDE format: hints not allowed",
    "Fragilità tattica: subisce sconfitte rapide (attacchi diretti efficaci).": "Tactical fragility: suffers quick losses (direct attacks work).",
    "Francese Tarrasch": "French, Tarrasch Variation",
    "Francese Winawer": "French, Winawer Variation",
    "Francese classica": "Classical French",
    "Francese di cambio": "Exchange French",
    "Francese, variante d'avanzata": "French, Advance Variation",
    "Funzione disattivata dal super admin": "Feature disabled by the super admin",
    "Gambetto Benko": "Benko Gambit",
    "Gambetto Danese": "Danish Gambit",
    "Gambetto Evans": "Evans Gambit",
    "Gambetto Réti accettato": "Réti Gambit Accepted",
    "Gambetto Scozzese": "Scotch Gambit",
    "Gambetto di Donna": "Queen's Gambit",
    "Gambetto di Donna accettato": "Queen's Gambit Accepted",
    "Gambetto di Donna rifiutato": "Queen's Gambit Declined",
    "Gambetto di Donna rifiutato (ortodossa)": "Queen's Gambit Declined (Orthodox)",
    "Gambetto di Re": "King's Gambit",
    "Gambetto di Re accettato (Kieseritzky)": "King's Gambit Accepted (Kieseritzky)",
    "Gambetto di Re rifiutato": "King's Gambit Declined",
    "Gioco non ancora giocabile": "Game not playable yet",
    "Gioco non trovato": "Game not found",
    "Gioco non trovato o non giocabile": "Game not found or not playable",
    "Hai già un'offerta pendente": "You already have a pending offer",
    "Hint riservato ai principianti: vittorie massime nel gioco per usarlo": "Hint reserved for beginners: maximum wins in the game to use it",
    "Il suggerimento è del giocatore al tratto": "The hint belongs to the player to move",
    "Inglese (siciliana in contromossa)": "English (Reversed Sicilian)",
    "Inglese simmetrica": "Symmetrical English",
    "L'analisi è disponibile solo per gli scacchi": "Analysis is available for chess only",
    "L'export PGN vale solo per gli scacchi": "PGN export applies to chess only",
    "La partita non è ancora conclusa": "The game is not finished yet",
    "La partita non è in corso": "The game is not in progress",
    "La posizione iniziale FEN vale solo per gli scacchi": "The FEN starting position applies to chess only",
    "Lato non valido (x oppure o)": "Invalid side (x or o)",
    "Lingua predefinita della voce (it, en)": "Default voice language (it, en)",
    "Livello Stockfish sconosciuto": "Unknown Stockfish level",
    "Livello del motore sconosciuto": "Unknown engine level",
    "Livello e provider insieme non hanno senso: il livello calibra il motore locale": "Level and provider together make no sense: the level calibrates the local engine",
    "Lunghezza massima del testo per richiesta (caratteri)": "Maximum text length per request (characters)",
    "Manca l'utente per un giocatore umano": "Missing user for a human player",
    "Monotonia in apertura": "Opening monotony",
    "Mossa non valida": "Invalid move",
    "Mosse IA in background (il client si aggiorna da solo; no = calcolo in linea)": "AI moves in the background (the client refreshes itself; no = inline computation)",
    "Nessun provider IA attivo (configura un token)": "No active AI provider (configure a token)",
    "Nessuna offerta da accettare": "No offer to accept",
    "Nessuna offerta da rifiutare": "No offer to decline",
    "Nimzo-Indiana (Rubinstein)": "Nimzo-Indian (Rubinstein)",
    "Nimzo-Indiana classica": "Classical Nimzo-Indian",
    "Nome del sito": "Site name",
    "Worker delle mosse IA (partite calcolate in parallelo; le altre aspettano)": "AI move workers (games computed in parallel; the rest wait)",
    "Stagione Elo corrente (cambiarla apre una stagione nuova)": "Current Elo season (changing it starts a new season)",
    "Non sei il giocatore al tratto in questa partita": "You are not the player to move in this game",
    "Numero massimo di partite consecutive (batch IA-vs-IA)": "Maximum number of consecutive games (AI-vs-AI batch)",
    "Numero massimo di partite consecutive: {n}": "Maximum number of consecutive games: {n}",
    "Olandese Leningrado": "Leningrad Dutch",
    "Partita Italiana": "Italian Game",
    "Partita Italiana (Giuoco Piano)": "Italian Game (Giuoco Piano)",
    "Partita Scozzese": "Scotch Game",
    "Partita Scozzese (variante Mieses)": "Scotch Game (Mieses Variation)",
    "Partita Scozzese classica": "Classical Scotch",
    "Partita Spagnola (Ruy López)": "Spanish Game (Ruy López)",
    "Partita Viennese": "Vienna Game",
    "Partita aperta": "Open Game",
    "Partita del centro": "Centre Game",
    "Partita già conclusa": "Game already finished",
    "Pausa anti-tilt: ": "Anti-tilt break: ",
    "Percorso del binario Stockfish (vuoto = STOCKFISH_PATH o ricerca nel PATH)": "Stockfish binary path (empty = STOCKFISH_PATH or PATH lookup)",
    "Pondering: il motore pensa durante il turno dell'umano (scacchi)": "Pondering: the engine thinks during the human's turn (chess)",
    "Precisione bassa: perde in media {acpl} centipedoni a mossa.": "Low accuracy: loses {acpl} centipawns per move on average.",
    "Provider IA attivo (vuoto = solo giocatore locale)": "Active AI provider (empty = local player only)",
    "Provider IA non disponibile al momento (errore o circuito aperto): riprova": "AI provider currently unavailable (error or open circuit): try again",
    "Provider IA sconosciuto": "Unknown AI provider",
    "Punti per una patta": "Points for a draw",
    "Punti per una sconfitta": "Points for a loss",
    "Punti per una vittoria": "Points for a win",
    "Puoi agire solo per il tuo lato": "You can only act for your own side",
    "Quattro cavalli (spagnola)": "Four Knights (Spanish)",
    "Re in centro": "King in the centre",
    "Registrazione in attesa di approvazione da parte del super admin": "Registration awaiting approval by the super admin",
    "Registrazioni disabilitate dall'amministratore": "Registrations disabled by the administrator",
    "Rende meno con l'apertura «{name}».": "Performs worse in the «{name}» opening.",
    "Riconoscimento del tilt (avviso soft dopo sconfitte rapide consecutive)": "Tilt detection (soft warning after consecutive quick losses)",
    "Ritardo minimo tra una mossa e l'altra dell'IA (millisecondi; 0 = nessuno)": "Minimum delay between AI moves (milliseconds; 0 = none)",
    "Ritardo prima della mossa dell'IA (millisecondi)": "Delay before the AI move (milliseconds)",
    "Réti (sistema principale)": "Réti (Main System)",
    "Scandinava moderna": "Modern Scandinavian",
    "Semimossa inesistente": "No such half-move",
    "Servono da 2 a {n} concorrenti diversi": "You need 2 to {n} distinct competitors",
    "Sessione non trovata": "Session not found",
    "Sessione non valida o scaduta": "Invalid or expired session",
    "Si può respingere solo una richiesta in attesa": "Only a pending request can be rejected",
    "Siciliana Alapin": "Sicilian, Alapin",
    "Siciliana Dragone (attacco Jugoslavo)": "Sicilian Dragon (Yugoslav Attack)",
    "Siciliana Kan": "Sicilian, Kan",
    "Siciliana Moscovita": "Sicilian, Moscow Variation",
    "Siciliana Najdorf": "Sicilian, Najdorf",
    "Siciliana Rossolimo": "Sicilian, Rossolimo",
    "Siciliana Scheveningen": "Sicilian, Scheveningen",
    "Siciliana Sveshnikov": "Sicilian, Sveshnikov",
    "Siciliana Taimanov": "Sicilian, Taimanov",
    "Siciliana chiusa": "Closed Sicilian",
    "Siciliana classica (Richter-Rauzer)": "Classical Sicilian (Richter-Rauzer)",
    "Siciliana, attacco Grand Prix": "Sicilian, Grand Prix Attack",
    "Sintesi vocale attiva (endpoint /tts)": "Speech synthesis enabled (/tts endpoint)",
    "Sistema Colle": "Colle System",
    "Sistema Londra": "London System",
    "Skill Level di Stockfish (0-20, 20 = piena forza)": "Stockfish Skill Level (0-20, 20 = full strength)",
    "Solo i giocatori possono annotare": "Only the players can annotate",
    "Solo un giocatore umano può farlo": "Only a human player can do that",
    "Spagnola aperta": "Open Spanish",
    "Spagnola chiusa (Ruy López)": "Closed Spanish (Ruy López)",
    "Spagnola di cambio": "Exchange Spanish",
    "Spagnola, difesa Berlinese": "Spanish, Berlin Defence",
    "Stockfish non disponibile per l'analisi": "Stockfish unavailable for analysis",
    "Storico non ricostruibile": "History cannot be reconstructed",
    "Suggerimenti disattivati dal super admin": "Hints disabled by the super admin",
    "Suggerimenti riservati ai principianti (max {n} vittorie)": "Hints reserved for beginners (max {n} wins)",
    "Suggerimento mossa (hint) attivo": "Move hint enabled",
    "Tempo di analisi del motore scacchi per mossa (millisecondi)": "Chess engine thinking time per move (milliseconds)",
    "Tempo di riflessione di Stockfish per mossa (millisecondi)": "Stockfish thinking time per move (milliseconds)",
    "Tempo scaduto: partita conclusa": "Time forfeit: game over",
    "Tende alla patta: conviene evitare le semplificazioni e tenere la tensione.": "Draw-prone: avoid simplifications and keep the tension.",
    "Tilt: BLOCCA le nuove partite di scacchi (default: solo avviso soft)": "Tilt: BLOCK new chess games (default: soft warning only)",
    "Tilt: fattore di peggioramento dell'ACPL rispetto alla propria media": "Tilt: ACPL worsening factor against one's own average",
    "Tilt: minuti di pausa forzata dall'ultima sconfitta (se il blocco è attivo)": "Tilt: minutes of forced break since the last loss (if blocking is on)",
    "Tilt: sconfitte consecutive che fanno scattare l'avviso": "Tilt: consecutive losses that trigger the warning",
    "Tilt: una sconfitta è «rapida» sotto queste semimosse": "Tilt: a loss is “quick” under this many plies",
    "Torneo non trovato": "Tournament not found",
    "Utente non trovato": "User not found",
    "Velocità di lettura (1.0 = normale)": "Reading speed (1.0 = normal)",
    "Voce per l'inglese (motore:voce — es. kitten:expr-voice-2-f)": "English voice (engine:voice — e.g. kitten:expr-voice-2-f)",
    "Voce per l'italiano (motore:voce — es. piper:it_IT-paola-medium)": "Italian voice (engine:voice — e.g. piper:it_IT-paola-medium)",
    "Volume dell'effetto sonoro (0-100)": "Sound effect volume (0-100)",
    "Voti minimi per fondare un gruppo": "Minimum votes to found a group",
    "arrocco assente o molto tardivo: il re resta esposto nel mediogioco": "castling absent or very late: the king stays exposed in the middlegame",
    "la donna esce nelle prime 5 mosse: bersaglio di sviluppo avversario con perdita di tempi": "the queen comes out within the first 5 moves: a development target that loses tempi",
    "la maggioranza dei blunder è una cattura: si prende il materiale anche quando la ripresa costa di più": "most blunders are captures: material is grabbed even when the recapture costs more",
    "lo stesso tipo di pezzo domina le prime mosse: sviluppo incompleto degli altri pezzi": "the same piece type dominates the first moves: the other pieces stay undeveloped",
    "{n} sconfitte di fila con una precisione peggiore del solito (ACPL recente {rec} contro una media di {avg})": "{n} losses in a row with worse accuracy than usual (recent ACPL {rec} against an average of {avg})",
    "{n} sconfitte rapide di fila (≤{plies} semimosse)": "{n} quick losses in a row (≤{plies} plies)",
    "«Spiegami questa mossa» in moviola (usa il provider IA attivo)": "“Explain this move” in the replay viewer (uses the active AI provider)",
    "È il turno dell'IA": "It is the AI's turn",
    # Gestione gruppi (inviti, ruoli, espulsioni)
    "Servono i gradi di fondatore o admin del gruppo": "You need founder or admin rank in the group",
    "Invito non trovato": "Invite not found",
    "L'invito non è per te": "The invite is not for you",
    "Invito già concluso": "Invite already settled",
    "È già membro del gruppo": "Already a member of the group",
    "Invito già in attesa": "Invite already pending",
    "Non è membro del gruppo": "Not a member of the group",
    "Il fondatore non può lasciare il gruppo": "The founder cannot leave the group",
    "Il fondatore non si espelle": "The founder cannot be expelled",
    "Un admin può espellere solo i member": "An admin can only expel members",
    "Solo il fondatore cambia i ruoli": "Only the founder changes roles",
    "Ruolo sconosciuto": "Unknown role",
    # Tornei umani
    "Formato di torneo sconosciuto": "Unknown tournament format",
    "Nome obbligatorio": "Name is required",
    "Solo i membri del gruppo possono organizzare": "Only group members can organize",
    "Le iscrizioni sono chiuse": "Registration is closed",
    "Torneo riservato ai membri del gruppo": "Tournament reserved for group members",
    "Sei già iscritto": "You are already registered",
    "Torneo al completo": "Tournament is full",
    "Il torneo è già avviato": "The tournament has already started",
    "Non sei iscritto": "You are not registered",
    "Servono almeno 2 iscritti": "At least 2 players are required",
    "Solo l'organizzatore avvia il torneo": "Only the organizer starts the tournament",
    # Sfide (inviti a giocare)
    "Sfida non trovata": "Challenge not found",
    "Sfida già conclusa": "Challenge already settled",
    "Non puoi sfidare te stesso": "You cannot challenge yourself",
    "Lato sconosciuto (x oppure o)": "Unknown side (x or o)",
    "Hai già una sfida in attesa": "You already have a pending challenge",
    "La sfida non è per te": "The challenge is not for you",
    "Puoi ritirare solo le tue sfide": "You can only withdraw your own challenges",
    # Notifiche (template parametrici, tradotti alla lettura)
    "{alias} ti sfida a {game}": "{alias} challenges you to {game}",
    "{alias} ha accettato la tua sfida a {game}": "{alias} accepted your challenge to {game}",
    "{alias} ha rifiutato la tua sfida a {game}": "{alias} declined your challenge to {game}",
    "Il gruppo «{group}» ti invita (da {alias})": "The group “{group}” invites you (from {alias})",
    "Torneo «{name}»: è pronta la tua partita del turno {round}": "Tournament “{name}”: your round {round} game is ready",
    "Hai vinto il torneo «{name}»!": "You won the tournament “{name}”!",
    "Torneo «{name}» concluso: vince {alias}": "Tournament “{name}” finished: {alias} wins",
}
