"""presenza online e partite a distanza

Revisione: 0002
Precedente: 0001
Creata il: 2026-07-05 20:39:22.329819
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("remote", sa.Boolean(), server_default="0", nullable=False))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_seen_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("last_seen_at")

    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.drop_column("remote")

    # ### end Alembic commands ###
