"""provider IA per lato

Revisione: 0003
Precedente: 0002
Creata il: 2026-07-05 21:47:38.365167
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("x_ai_provider", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("o_ai_provider", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.drop_column("o_ai_provider")
        batch_op.drop_column("x_ai_provider")

    # ### end Alembic commands ###
