"""offerta di patta

Revisione: 0006
Precedente: 0005
Creata il: 2026-07-07 18:12:18.927846
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("draw_offer", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.drop_column("draw_offer")

    # ### end Alembic commands ###
